USE [IAS]
GO

/****** Object:  Table [dbo].[1K_2012]    Script Date: 17.12.2012 23:18:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[1K_2012](
	[code_dg] [nvarchar](3) NOT NULL,
	[calc_date] [date] NOT NULL,
	[pos_1] [int] NULL,
	[pos_2] [int] NULL,
	[pos_3] [int] NULL,
	[pos_4] [int] NULL,
	[pos_5] [int] NULL,
	[pos_6] [int] NULL,
	[pos_7] [int] NULL,
	[pos_8] [int] NULL,
	[pos_9] [int] NULL,
	[pos_10] [int] NULL,
	[pos_11] [int] NULL,
	[pos_12] [int] NULL,
	[pos_13] [int] NULL,
	[pos_14] [int] NULL,
	[pos_15] [int] NULL,
	[pos_16] [int] NULL,
	[pos_17] [int] NULL,
	[pos_18] [int] NULL,
	[pos_19] [int] NULL,
	[pos_20] [int] NULL,
	[pos_21] [int] NULL,
	[pos_22] [int] NULL,
	[pos_23] [int] NULL,
	[pos_24] [int] NULL,
	[pos_25] [int] NULL,
	[pos_26] [int] NULL,
	[pos_27] [int] NULL,
	[pos_28] [int] NULL,
	[pos_29] [int] NULL,
	[pos_30] [int] NULL,
	[pos_31] [int] NULL,
	[pos_32] [int] NULL,
	[pos_33] [int] NULL,
	[pos_34] [int] NULL,
	[pos_35] [int] NULL,
	[pos_36] [int] NULL,
	[pos_37] [int] NULL,
	[pos_38] [int] NULL,
	[pos_39] [int] NULL,
	[pos_40] [int] NULL,
	[pos_41] [int] NULL,
	[pos_42] [int] NULL,
	[pos_43] [int] NULL,
	[pos_44] [int] NULL,
	[pos_45] [int] NULL,
	[pos_46] [int] NULL,
	[pos_47] [int] NULL,
	[pos_48] [int] NULL,
	[pos_49] [int] NULL,
	[pos_50] [int] NULL,
	[pos_51] [int] NULL,
	[pos_52] [int] NULL,
	[pos_53] [int] NULL,
	[pos_54] [int] NULL,
	[pos_55] [int] NULL,
	[pos_56] [int] NULL,
	[pos_57] [int] NULL,
	[pos_58] [int] NULL,
	[pos_59] [int] NULL,
	[pos_60] [int] NULL,
	[pos_61] [int] NULL,
	[pos_62] [int] NULL,
	[pos_63] [int] NULL,
	[pos_64] [int] NULL,
	[pos_65] [int] NULL,
	[pos_66] [int] NULL,
	[pos_67] [int] NULL,
	[pos_68] [int] NULL,
	[pos_69] [int] NULL,
	[pos_70] [int] NULL,
	[pos_71] [int] NULL,
	[pos_72] [int] NULL,
	[pos_73] [int] NULL,
	[pos_74] [int] NULL,
	[pos_75] [int] NULL,
	[pos_76] [int] NULL,
	[pos_77] [int] NULL,
	[pos_78] [int] NULL,
	[pos_79] [int] NULL,
	[pos_80] [int] NULL,
	[pos_81] [int] NULL,
	[pos_82] [int] NULL,
	[pos_83] [int] NULL,
	[pos_84] [int] NULL,
	[pos_85] [int] NULL,
	[pos_86] [int] NULL,
	[pos_87] [int] NULL,
	[pos_88] [int] NULL,
	[pos_89] [int] NULL,
	[pos_90] [int] NULL,
	[pos_91] [int] NULL,
	[pos_92] [int] NULL,
	[pos_93] [int] NULL,
	[pos_94] [int] NULL,
	[pos_95] [int] NULL,
	[pos_96] [int] NULL,
	[pos_97] [int] NULL,
	[pos_98] [int] NULL,
	[pos_99] [int] NULL,
	[pos_100] [int] NULL,
	[pos_101] [int] NULL,
	[pos_102] [int] NULL,
	[pos_103] [int] NULL,
	[pos_104] [int] NULL,
	[pos_105] [int] NULL,
	[pos_106] [int] NULL,
	[pos_107] [int] NULL,
	[pos_108] [int] NULL,
	[pos_109] [int] NULL,
	[pos_110] [int] NULL,
	[pos_111] [int] NULL,
	[pos_112] [int] NULL,
	[pos_113] [int] NULL,
	[pos_114] [int] NULL,
	[pos_115] [int] NULL,
	[pos_116] [int] NULL,
	[pos_117] [int] NULL,
	[pos_118] [int] NULL,
	[pos_119] [int] NULL,
	[pos_120] [int] NULL,
	[pos_121] [int] NULL,
	[pos_122] [int] NULL,
	[pos_123] [int] NULL,
	[pos_124] [int] NULL,
	[pos_125] [int] NULL,
	[pos_126] [int] NULL
) ON [PRIMARY]

GO


